### ISSUE TITLE
Injector fails if p2 is installed.

### ISSUE THREAD

**Issue by jewome62** [SBPrime/AsyncWorldEdit-Premium#159]
### Version
Spigot : git-Spigot-29ab5e4-2bc7d1d (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
AsyncWorldEdit-Premium : v3.6.0-rc-03
WorldEdit: v7.0.0-beta-04;17f52cb

### Precision
There are no awe on this server previoulsy, so no config to purge.
After load (with error) i have no config file available

### Log
```
[12:02:36] [Server thread/INFO]: [P2] Force loading WorldEdit
[12:02:36] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v7.0.0-beta-04;17f52cb
[12:02:36] [Server thread/INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_13_R2_2 as the Bukkit adapter
[12:02:36] [Server thread/INFO]: [WorldEdit] Default configuration file written: config.yml
[12:02:36] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[12:02:36] [Server thread/INFO]: [P2] Testing platform capabilities
[12:02:36] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v4.3.62
[12:02:36] [Server thread/INFO]: [AsyncWorldEdit] Loading AsyncWorldEdit v3.6.0-rc-03
[12:02:36] [Server thread/INFO]: [AsyncWorldEdit] Injector platform set to: InjectorBukkit
[12:02:36] [Server thread/INFO]: [AsyncWorldEdit] Injecting WorldEdit classes...
[12:02:36] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.math.BlockVector2
[12:02:36] [Server thread/INFO]: [AsyncWorldEdit] ****************************
[12:02:36] [Server thread/INFO]: [AsyncWorldEdit] * CLASS INJECTION FAILED!! *
[12:02:36] [Server thread/INFO]: [AsyncWorldEdit] ****************************
[12:02:36] [Server thread/INFO]: [AsyncWorldEdit] * AsyncWorldEdit won't work properly.
[12:02:36] [Server thread/INFO]: [AsyncWorldEdit] *
[12:02:36] [Server thread/INFO]: [AsyncWorldEdit] * Exception: java.lang.ClassFormatError
[12:02:36] [Server thread/INFO]: [AsyncWorldEdit] * Error message: Unable to invoke dynamic method. loader (instance of  org/bukkit/plugin/java/PluginClassLoader): attempted  duplicate class definition for name: "com/sk89q/worldedit/math/BlockVector2"
[12:02:36] [Server thread/INFO]: [AsyncWorldEdit] * Stack: 
[12:02:36] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.ClassInjectorBukkit.injectClass(ClassInjectorBukkit.java:119)
[12:02:36] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.modiffyClasses(InjectorCore.java:260)
[12:02:36] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.initialize(InjectorCore.java:173)
[12:02:36] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.InjectorBukkit.onEnable(InjectorBukkit.java:89)
[12:02:36] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.AsyncWorldEditBukkit.onLoad(AsyncWorldEditBukkit.java:248)
[12:02:36] [Server thread/INFO]: [AsyncWorldEdit] * org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:328)
[12:02:36] [Server thread/INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:213)
[12:02:36] [Server thread/INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:697)
[12:02:36] [Server thread/INFO]: [AsyncWorldEdit] * java.lang.Thread.run(Thread.java:748)
[12:02:36] [Server thread/INFO]: [AsyncWorldEdit] ****************************
[12:02:36] [Server thread/INFO]: [AsyncWorldEdit] Unable to initialize injector.
[12:02:36] [Server thread/INFO]: [AsyncWorldEdit] ERROR: Unable to enable the injector.
[12:02:36] [Server thread/INFO]: [Vault] Loading Vault v1.7.1-b91
[12:02:36] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.4.0
[12:02:36] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.13.2) has not yet been tested! Proceed with caution.
[12:02:36] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v7.0.0-beta-04;17f52cb
```

Related With #158

**Comment by Kikisito** [comment]
I have the same error

**Comment by SBPrime** [comment]
Unfortunately I'm unable to reproduce the problem. Could you please provide a link to the P2 jar witch you are using + your config?

For now could you try this:
1. Open the AWE jar using your favorite archive viewer.
2. Open plugin.yml
3. Find entry: loadbefore
4. Change it from: ```loadbefore: [WorldEdit, WorldGuard]``` to ```loadbefore: [WorldEdit, WorldGuard, PlotSquared]```
5. Save the file (make sure that you saved it in the jar),
6. Save and close the AWE jar
7. Upload to server and restart.

**Comment by SBPrime** [comment]
Ok now I know why I was unable to reproduce. I used plotsquered compiled from MASTER. When I used the prerelease the error startet showing up.  The file that is causing problems:

https://github.com/IntellectualSites/PlotSquared/blame/4.0-pre-breaking/Bukkit/src/main/java/com/github/intellectualsites/plotsquared/bukkit/BukkitMain.java

The file in master:

https://github.com/IntellectualSites/PlotSquared/blame/master/Bukkit/src/main/java/com/plotsquared/bukkit/BukkitMain.java

Code thats causing problems:
```
package com.github.intellectualsites.plotsquared.bukkit;

...

public final class BukkitMain extends JavaPlugin implements Listener, IPlotMain {

    ...

    static {
        ...
        // Force WorldEdit to load
        try {
            System.out.println("[P2] Force loading WorldEdit");
            if (!manager.isPluginEnabled("WorldEdit")) {
                manager.enablePlugin(WorldEditPlugin.getPlugin(WorldEditPlugin.class));
            }
            System.out.println("[P2] Testing platform capabilities");
            WorldEdit.getInstance().getPlatformManager().queryCapability(Capability.GAME_HOOKS);
        } catch (final Throwable throwable) {
            throw new IllegalStateException(
                "Failed to force load WorldEdit." + " Road schematics will fail to generate",
                throwable);
        }
    }

    ...
}
```

Everything seams to work fine with the build from master.

**Comment by Raphy123** [comment]
don't work for me :/ :'(

The jar of P2 : http://www.mediafire.com/file/8xf34nat52bh3fa/PlotSquared-Bukkit-4.18.12.25-edc7583-2105.jar

Could you send me the jar ?

**Comment by jewome62** [comment]
Hello @SBPrime 
I have try to change plugin.yml without success because it say plugin.yml is invalid.
I think there are a checksum verify ? no ?

Edit:
I try lastest build of Plotsquared by success
```
05.01 22:45:35 [Server] INFO [AsyncWorldEdit] Enabling AsyncWorldEdit v3.6.0-rc-03 05.01 22:45:35 [Server] INFO [AsyncWorldEdit] Warning: Unable to get class com.sk89q.worldedit.extent.reorder.MultiStageReorder$Stage3Committer 05.01 22:45:35 [Server] INFO [AsyncWorldEdit] Warning: Unable to get class com.sk89q.worldedit.extent.reorder.MultiStageReorder$Stage3Committer 05.01 22:45:36 [Server] INFO [AsyncWorldEdit] Platform set to Bukkit API 05.01 22:45:36 [Server] INFO [AsyncWorldEdit] =================================================================================== 05.01 22:45:36 [Server] INFO [AsyncWorldEdit] = ___ _ __ __ ________ ___ __ = 05.01 22:45:36 [Server] INFO [AsyncWorldEdit] = / | _______ ______ ____| | / /___ _____/ /___/ / ____/___/ (_) /_ = 05.01 22:45:36 [Server] INFO [AsyncWorldEdit] = / /| | / ___/ / / / __ \/ ___/ | /| / / __ \/ ___/ / __ / __/ / __ / / __/ = 05.01 22:45:36 [Server] INFO [AsyncWorldEdit] = / ___ |(__ ) /_/ / / / / /__ | |/ |/ / /_/ / / / / /_/ / /___/ /_/ / / /_ = 05.01 22:45:36 [Server] INFO [AsyncWorldEdit] = /_/ |_/____/\__, /_/ /_/\___/ |__/|__/\____/_/ /_/\__,_/_____/\__,_/_/\__/ = 05.01 22:45:36 [Server] INFO [AsyncWorldEdit] = /____/ = 05.01 22:45:36 [Server] INFO [AsyncWorldEdit] = Author: SBPrime = 05.01 22:45:36 [Server] INFO [AsyncWorldEdit] = = 05.01 22:45:36 [Server] INFO [AsyncWorldEdit] =================================================================================== 05.01 22:45:36 [Server] INFO [AsyncWorldEdit] Undo cleanup started... 05.01 22:45:36 [Server] INFO [AsyncWorldEdit] ...undo cleanup done. 05.01 22:45:36 [Server] INFO [AsyncWorldEdit] No matching adapter found for Bukkit.v1_13_R2, DirectChunkAPI disabled 05.01 22:45:36 [Server] INFO [AsyncWorldEdit] PlotMeFix set to class org.primesoft.asyncworldedit.plotme.NullFix. 05.01 22:45:36 [Server] INFO [AsyncWorldEdit] New class factory set to: org.primesoft.asyncworldedit.asyncinjector.async.AsyncClassFactory 05.01 22:45:36 [Server] INFO [AsyncWorldEdit] Enabled
```
I connect to server to try

edit : I confirm that's work

**Comment by Kikisito** [comment]
> Ok now I know why I was unable to reproduce. I used plotsquered compiled from MASTER. When I used the prerelease the error startet showing up. The file that is causing problems:
> 
> https://github.com/IntellectualSites/PlotSquared/blame/4.0-pre-breaking/Bukkit/src/main/java/com/github/intellectualsites/plotsquared/bukkit/BukkitMain.java
> 
> The file in master:
> 
> https://github.com/IntellectualSites/PlotSquared/blame/master/Bukkit/src/main/java/com/plotsquared/bukkit/BukkitMain.java
> 
> Code thats causing problems:
> 
> ```
> package com.github.intellectualsites.plotsquared.bukkit;
> 
> ...
> 
> public final class BukkitMain extends JavaPlugin implements Listener, IPlotMain {
> 
>     ...
> 
>     static {
>         ...
>         // Force WorldEdit to load
>         try {
>             System.out.println("[P2] Force loading WorldEdit");
>             if (!manager.isPluginEnabled("WorldEdit")) {
>                 manager.enablePlugin(WorldEditPlugin.getPlugin(WorldEditPlugin.class));
>             }
>             System.out.println("[P2] Testing platform capabilities");
>             WorldEdit.getInstance().getPlatformManager().queryCapability(Capability.GAME_HOOKS);
>         } catch (final Throwable throwable) {
>             throw new IllegalStateException(
>                 "Failed to force load WorldEdit." + " Road schematics will fail to generate",
>                 throwable);
>         }
>     }
> 
>     ...
> }
> ```
> Everything seams to work fine with the build from master.

So, the PlotSquared's author needs to fix this?

**Comment by jewome62** [comment]
Hello @SBPrime 
In reality, in master that's version for 1.12
To download 1.13 version, use need use https://ci.athion.net/job/PlotSquared-Breaking/lastSuccessfulBuild/artifact/target/PlotSquared-Bukkit-4.88.jar

Thanks

Additional Question : I have install BountifulAPI-1.6.4.jar (latest, compatible 1.13) and it not used.
```yaml
messages:
        #Whether or not to show progress using BarAPI
        progress-bar: true
        #minimum number of blocks to display the progress bar
        progress-bar-min: 100
```
I don't know if i must do something other ?

**Comment by Kikisito** [comment]
It doesn't work for me yet. I'm using the latest P2's build and I've changed my plugin.yml

**Comment by SBPrime** [comment]
The fix with changes in plugin.yml was a shot n the dark. I was using a P2 compiled from master and that version seams to work without any problems. The prerelease is broken.

Regarding BountifulAPI-1.6.4.jar did you enable the bridge in AWE plugins?

**Comment by jewome62** [comment]
@SBPrime Hello
I have retested edit plugin.yml with https://ci.athion.net/job/PlotSquared-Breaking/lastSuccessfulBuild/artifact/target/PlotSquared-Bukkit-4.88.jar
And i have same problem. 

PlotSquared master doesn't work with 1.13 => https://github.com/IntellectualSites/PlotSquared/issues/2220
This is only 1.12 and less
Exemple : with Plotsquared master, i can remove plot, World edit restriction don't work

For  BountifulAPI-1.6.4.jar  i forgot to remove .dis extension on plugin directory

**Comment by SBPrime** [comment]
@jewome62 Since they are using static constructors to force load worldedit. In my opinion this is an extremely bad solution. It breaks how I hook into WE that there is no reliable way of working around it. 

Bottom line is that if they keep that piece of code I'll be forced to force unload WorldEdit. And that in consequence might break P2.

**Comment by Draycia** [comment]
Constructors in Java cannot be marked static. Can you clarify what you mean by static constructor?
Edit: Apparently `static constructor` isn't `static ClassName()` and instead means `static { }`.

**Comment by Citymonstret** [comment]
We need that piece of code to have worldedit be available during world generation, as we are loading our plugin during startup, rather than after world generation. You say that this is “an extremely bad solution”, yet we haven’t had a single problem with other than with your plugin. If it breaks how YOU  hook into WorldEdit, then there’s a very big chance that you are doing things in a bad way. 

If you rely on injecting code in WorldEdit (which is in fact a very bad way of doing it, but meh) then I suggest you make sure to load your plugin earlier, possibly during startup, in which case we’d both be happy. So yes, there are reliable ways of working around it.

**Comment by jewome62** [comment]
So @SBPrime Do you this it's possible to injectClass before PlotSquared try to load WorldEdit ?
I try with depend into plugin.yml without success

**Comment by SBPrime** [comment]
@Draycia Yes I meant the ```static {}``` block. I heard 3 names for it: "static constructor", "static initialization block"  and "initializer block".

@Sauilitired 
> We need that piece of code to have worldedit be available during world generation, as we are loading our plugin during startup, rather than after world generation

Still the onLoad should be called before any world generation or loading. I have my plugin set to load on STARTUP but I do all the preparations in onLoad. This is called way before bukkit starts loading the worlds (I'm not sure but I think that onEnabled is also called before world loading). My question is why in static? why not in onLoad or onEnabled (or in the constructor?).

| You say that this is “an extremely bad solution”, yet we haven’t had a single problem with other than with your plugin.
I'm not saying  it will cause problems. I'm only saying that this is "a bad solution" or "a bad code smell", at least this is what I was told, in my entire professional  life. In all companies that I worked at it was considered a bad design. But I'm not judging, its your code, your design. 

| If it breaks how YOU hook into WorldEdit, then there’s a very big chance that you are doing things in a bad way.
Breaks my code because my plugin needs to be the first one that handles the WorldEdit classes. Point taken. It might have been designed better. I could have used agents to modify the classes, or I could simply force unload WorldEdit. The problem hear is that I respect every developer in the community (except those that are rude) therefore I don't wan't to write code that would in 99% break their plugins. 

| If you rely on injecting code in WorldEdit (which is in fact a very bad way of doing it, but meh)
Unfortunately because of the changes in WorldEdit the only solution is to modify the code of WE it needs to be done at runtime (or once per plugin load). I tried to work with the WE team couple of years ago but the attitude was extremely toxic on their end (I'll say only that: I consider rude making fun of someone that is trying to improve your plugin). So if you did not have a chance to look at my work, and what is required to hook into WorldEdit please don't judge.

| you make sure to load your plugin earlier, possibly during startup, in which case we’d both be happy.
Now this is the real problem. I do make sure that my plugin is loaded before everything else. Plugin set to STARTUP, main code executed in onLoad. Unfortunately this will fail if some other plugin uses does something unexpected in constructor or in initialization block (your case). Why? It simple if you look at how bukkit loads plugins:
1. invoke the **pluginManager.loadPlugins(plugin-directory)**
2. execute the **File.listFiles** witch return all the plugins (in random order: http://www.theeggeadventure.com/wikimedia/index.php/Java_File.listFiles_order)

**for each plugin file:** 
3. load the descriptor
4. make sure that a plugin of the same name is not already loaded
5. process the soft and normal dependencies (only store)
6. process the "load before" (this is added as soft dependency)

**for each plugin to load:** 
7. check if all dependencies and soft dependencies are loaded (if not continue to next plugin and retry later)
8. create a class loader for the plugin
9. get the Class for the main plugin class
10. JAVA: calls the static initializer block
11. create new instance of the class
12. JAVA: call the constructor

**For each plugin that the main class was created:** 
13. call the onLoaded

**For each plugin that has STARTUP:** 
14. call the onEnabled

**After world is loaded**
**For each plugin that has POSTWORLD:** 
15. call the onEnabled

As you can see I could add my injection code in a static initializer, but I simply consider this a bad practice. But if thats what I need to do then let it be. Unfortunately I won't know each and every plugin that tries to use WorldEdit.

**Comment by SBPrime** [comment]
Fixed in rc-04

**Comment by CinnamonLambda** [comment]
Works a charm, thank you.

**Comment by x1p** [comment]
Almost
```
[23:24:05 INFO]: X1pPlayer issued server command: //set stone
[23:24:05 WARN]: Exception in thread "Thread-31" java.lang.NoSuchMethodError: com.sk89q.worldedit.history.change.BlockChange.getCurrent()Lcom/sk89q/worldedit/world/block/BlockStateHolder;
[23:24:05 WARN]: at org.primesoft.asyncworldedit.changesetSerializer.serializers.SerializerBlockChange.serialize(SerializerBlockChange.java:98)
[23:24:05 WARN]: at org.primesoft.asyncworldedit.changesetSerializer.SerializerManager.serialize(SerializerManager.java:502)
[23:24:05 WARN]: at org.primesoft.asyncworldedit.changesetSerializer.SerializerManager.save(SerializerManager.java:473)
[23:24:05 WARN]: at org.primesoft.asyncworldedit.changesetSerializer.SerializerManager.save(SerializerManager.java:313)
[23:24:05 WARN]: at org.primesoft.asyncworldedit.worldedit.history.changeset.FileChangeSet.save(FileChangeSet.java:210)
[23:24:05 WARN]: at org.primesoft.asyncworldedit.worldedit.history.changeset.FileChangeSetManager.saveLoop(FileChangeSetManager.java:126)
[23:24:05 WARN]: at java.lang.Thread.run(Thread.java:748)
[23:24:16 INFO]: X1pPlayer issued server command: //undo
```
Set stone is performed. Undo does nothing. Undo files ts.1682a6a71c7.f11b54a4.0 are 0 bytes.

**Comment by jewome62** [comment]
@SBPrime That's work 
you are the best

**Comment by SBPrime** [comment]
@x1p You are using a dev build of WorldEdit. I support only beta builds. When WE releases new beta I'll update to it. Support for latest dev build will be added only if I can make it work with dev + beta.

**Comment by x1p** [comment]
@SBPrime Ah ok. I like to live on the edge ;-)

Beta-04 works indeed. (And places blocks more regularly).
